Repository sai-github/chmod777-frontend, pull requests merged in 2021-05, with the labels that each got.

#2 docs: add section on starting and scripts with project
  README.md
Labels: documentation

#5 doc changes related to repo name
  README.md
Labels: maintain

#11 feat(faq): add, update, delete faqs
  src/components/manage-faq/ManageFaq.js
  src/theme.js
Labels: new feat

#13 Fixed spinner problem while login and signup
  src/components/auth/Login.js
  src/components/auth/Signup.js
Labels: bug

#17 generate tokens from dashboard
  src/App.js
  src/components/dashboard/Dashboard.js
  src/components/dashboard/PrivateDashboard.js
  src/components/header/Header.js
Labels: new feat

#18 fix(bugsummary): use base64 as img src
  src/components/bug-summary/BugSummary.js
Labels: bug
